# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#20211f\033\\"
printf "\033]4;1;#7b8b7a\033\\"
printf "\033]4;2;#8a8d75\033\\"
printf "\033]4;3;#aca98e\033\\"
printf "\033]4;4;#99b0a1\033\\"
printf "\033]4;5;#b4baa8\033\\"
printf "\033]4;6;#b0c0cb\033\\"
printf "\033]4;7;#faffff\033\\"
printf "\033]4;8;#888c83\033\\"
printf "\033]4;9;#99ad98\033\\"
printf "\033]4;10;#acb092\033\\"
printf "\033]4;11;#d7d3b1\033\\"
printf "\033]4;12;#bfdcc9\033\\"
printf "\033]4;13;#e1e8d2\033\\"
printf "\033]4;14;#dcf0fd\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#20211f\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
