brew "gh"
brew "fastfetch"
brew "fish"
brew "hellwal"
brew "starship"

cask "claude-code"
cask "figma"
cask "figma-agent"
cask "ghostty@tip"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale-app"
cask "thebrowsercompany-dia"
cask "visual-studio-code"
